default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: nl2sql_development

test:
  <<: *default
  database: nl2sql_test

production:
  <<: *default
  database: nl2sql_production
  username: nl2sql
  password: <%= ENV['NL2SQL_DATABASE_PASSWORD'] %>
